# Site settings

repository: saptab/modern-distributed-computing-with-AI-Agents

course_name: CSC 36000 - Modern Distributed Computing with AI Agents
course_description: "This course immerses students in distributed systems and advanced AI agent technology, including LLMs, VLMs, federated/decentralized ML, and real-world agent deployments. Both theory and practical work are emphasized, with focus on architecture, coordination, JAX-based learning, safety, scalability, and applications in diverse environments."
course_semester: "Fall 2025"

baseurl: "/modern-distributed-computing-with-AI-Agents" # the subpath of your site, e.g. /blog/
url: "https://saptab.github.io/" # the base hostname & protocol for your site

schoolname: "City College of New York"
schoolurl: "https://www.ccny.cuny.edu/"
twitter_username: CityCollegeNY

address: |
    Department of Computer Science
    City College of New York
    New York, NY

instructor: "Professor Saptarashmi Bandyopadhyay"

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
